services:
  mongodb:
    image: mongo:7
    container_name: postloop-template-mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./.data/mongo-docker:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', 'db.runCommand({ ping: 1 }).ok']
      interval: 5s
      timeout: 5s
      retries: 20
